services:
  db:
    image: postgres
    container_name: xrm-postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: xrmdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build:
      context: ./backend/mini-xrm
    container_name: xrm-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/xrmdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: xrm-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:4200"

volumes:
  postgres_data:
    name: xrm-postgres-data
