spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/xrmdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
